services:
  # This service runs database migrations and then exits.
  migrations:
    build:
      context: ./whatsapp_gateway
      dockerfile: Dockerfile
    command: sh -c "echo 'Running database migrations...' && flask db upgrade && echo 'Migrations complete.'"
    depends_on:
      postgres:
        condition: service_healthy
    # COPIED ALL ENVIRONMENT VARIABLES FROM whatsapp-gateway
    environment:
      - FLASK_APP=src.main
      - PYTHONPATH=/app
      - WHATSAPP_API_VERSION=v23.0
      - ECOMMERCE_API_URL=http://ecommerce-integration:5002
      - AI_SERVICE_URL=http://ai-conversation-engine:5001
      - SHOPIFY_STORE_URL=https://feelori.myshopify.com
      - DATABASE_URL_FILE=/run/secrets/database_url.txt
      - WHATSAPP_ACCESS_TOKEN_FILE=/run/secrets/whatsapp_access_token.txt
      - WHATSAPP_PHONE_NUMBER_ID_FILE=/run/secrets/whatsapp_phone_number_id.txt
      - WHATSAPP_VERIFY_TOKEN_FILE=/run/secrets/whatsapp_verify_token.txt
      - INTERNAL_API_KEY_FILE=/run/secrets/internal_api_key.txt
      - GEMINI_API_KEY_FILE=/run/secrets/gemini_api_key.txt
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key.txt
      - WHATSAPP_WEBHOOK_SECRET_FILE=/run/secrets/webhook_secret.txt
      - API_KEY_FILE=/run/secrets/api_key.txt
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password.txt
    volumes:
      - C:/Users/hp/Documents/feelori-secrets:/run/secrets:ro
      - ./whatsapp_gateway:/app
      - ./shared:/app/shared:ro
    networks:
      - ai-assistant-network

  whatsapp-gateway:
    build:
      context: ./whatsapp_gateway
      dockerfile: Dockerfile
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - ai-assistant-network
    environment:
      - FLASK_APP=src.main
      - PYTHONPATH=/app
      - WHATSAPP_API_VERSION=v23.0
      - ECOMMERCE_API_URL=http://ecommerce-integration:5002
      - AI_SERVICE_URL=http://ai-conversation-engine:5001
      - SHOPIFY_STORE_URL=https://feelori.myshopify.com
      - DATABASE_URL_FILE=/run/secrets/database_url.txt
      - WHATSAPP_ACCESS_TOKEN_FILE=/run/secrets/whatsapp_access_token.txt
      - WHATSAPP_PHONE_NUMBER_ID_FILE=/run/secrets/whatsapp_phone_number_id.txt
      - WHATSAPP_VERIFY_TOKEN_FILE=/run/secrets/whatsapp_verify_token.txt
      - INTERNAL_API_KEY_FILE=/run/secrets/internal_api_key.txt
      - GEMINI_API_KEY_FILE=/run/secrets/gemini_api_key.txt
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key.txt
      - WHATSAPP_WEBHOOK_SECRET_FILE=/run/secrets/webhook_secret.txt
      - API_KEY_FILE=/run/secrets/api_key.txt
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password.txt
      - SHOPIFY_ACCESS_TOKEN_FILE=/run/secrets/shopify_access_token.txt
    volumes:
      - C:/Users/hp/Documents/feelori-secrets:/run/secrets:ro
      - ./shared:/app/shared:ro
      - ./whatsapp_gateway:/app
      - whatsapp_data:/app/data

  celery-worker:
    build:
      context: ./whatsapp_gateway
      dockerfile: Dockerfile
    command: celery -A src.tasks:celery_app worker --loglevel=info --concurrency=2
    depends_on:
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - ai-assistant-network
    environment:
      - FLASK_APP=src.main
      - PYTHONPATH=/app
      - WHATSAPP_API_VERSION=v23.0
      - ECOMMERCE_API_URL=http://ecommerce-integration:5002
      - AI_SERVICE_URL=http://ai-conversation-engine:5001
      - SHOPIFY_STORE_URL=https://feelori.myshopify.com
      - DATABASE_URL_FILE=/run/secrets/database_url.txt
      - INTERNAL_API_KEY_FILE=/run/secrets/internal_api_key.txt
      - GEMINI_API_KEY_FILE=/run/secrets/gemini_api_key.txt
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key.txt
      - WHATSAPP_ACCESS_TOKEN_FILE=/run/secrets/whatsapp_access_token.txt
      - WHATSAPP_PHONE_NUMBER_ID_FILE=/run/secrets/whatsapp_phone_number_id.txt
      - WHATSAPP_VERIFY_TOKEN_FILE=/run/secrets/whatsapp_verify_token.txt
      - WHATSAPP_WEBHOOK_SECRET_FILE=/run/secrets/webhook_secret.txt
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password.txt
      - SHOPIFY_ACCESS_TOKEN_FILE=/run/secrets/shopify_access_token.txt
    volumes:
      - C:/Users/hp/Documents/feelori-secrets:/run/secrets:ro
      - ./shared:/app/shared:ro
      - ./whatsapp_gateway:/app
      - whatsapp_data:/app/data

  ai-conversation-engine:
    build:
      context: ./ai_conversation_engine
      dockerfile: Dockerfile
    depends_on:
      - otel-collector
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/ai/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - ai-assistant-network
    environment:
      - FLASK_APP=src.main
      - PYTHONPATH=/app
      - ALLOWED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080
      - ECOMMERCE_API_URL=http://ecommerce-integration:5002
      - SHOPIFY_STORE_URL=https://feelori.myshopify.com
      - GEMINI_API_KEY_FILE=/run/secrets/gemini_api_key.txt
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key.txt
      - INTERNAL_API_KEY_FILE=/run/secrets/internal_api_key.txt
      - DATABASE_URL_FILE=/run/secrets/database_url.txt
      - WHATSAPP_ACCESS_TOKEN_FILE=/run/secrets/whatsapp_access_token.txt
      - WHATSAPP_PHONE_NUMBER_ID_FILE=/run/secrets/whatsapp_phone_number_id.txt
      - WHATSAPP_VERIFY_TOKEN_FILE=/run/secrets/whatsapp_verify_token.txt
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password.txt
      - SHOPIFY_ACCESS_TOKEN_FILE=/run/secrets/shopify_access_token.txt
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318/v1/traces
      - REQUEST_TIMEOUT=15
    volumes:
      - C:/Users/hp/Documents/feelori-secrets:/run/secrets:ro
      - ./ai_conversation_engine/src:/app/src
      - ./shared:/app/shared:ro

  ecommerce-integration:
    build:
      context: ./ecommerce_integration
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/ecommerce/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - ai-assistant-network
    environment:
      - FLASK_APP=src.main
      - PYTHONPATH=/app
      - SHOPIFY_STORE_URL=https://feelori.myshopify.com
      - SHOPIFY_ACCESS_TOKEN_FILE=/run/secrets/shopify_access_token.txt
      - DATABASE_URL_FILE=/run/secrets/database_url.txt
      - INTERNAL_API_KEY_FILE=/run/secrets/internal_api_key.txt
    volumes:
      - C:/Users/hp/Documents/feelori-secrets:/run/secrets:ro
      - ./ecommerce_integration/src:/app/src
      - ./shared:/app/shared:ro

  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - ai-assistant-network

  redis:
    image: redis:7-alpine
    command: sh -c "exec redis-server --requirepass \"$$(cat /run/secrets/redis_password.txt)\""
    ports:
      - "6379:6379"
    volumes:
      - C:/Users/hp/Documents/feelori-secrets:/run/secrets:ro
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ai-assistant-network

  postgres:
    image: pgvector/pgvector:pg15
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ai_assistant", "-d", "ai_assistant"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - ai-assistant-network
    environment:
      - POSTGRES_DB=ai_assistant
      - POSTGRES_USER=ai_assistant
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password.txt
    volumes:
      - C:/Users/hp/Documents/feelori-secrets:/run/secrets:ro
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - whatsapp-gateway
      - ai-conversation-engine
      - ecommerce-integration
      - admin-dashboard
    restart: unless-stopped
    networks:
      - ai-assistant-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.106.0
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "4318:4318"
      - "4317:4317"
    restart: unless-stopped
    networks:
      - ai-assistant-network
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml

volumes:
  whatsapp_data:
  redis_data:
  postgres_data:

networks:
  ai-assistant-network:
    driver: bridge