"""Auto-migration on startup

Revision ID: 02d65e75ec5a
Revises: ef43048de430
Create Date: 2025-07-26 15:15:27.868204

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '02d65e75ec5a'
down_revision = 'ef43048de430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
