"""Auto-migration on startup

Revision ID: 06e4dfbd347f
Revises: 842f472ee269
Create Date: 2025-07-26 13:09:55.480873

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '06e4dfbd347f'
down_revision = '842f472ee269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
