"""Auto-migration on startup

Revision ID: 13973eed5512
Revises: 92abe68dc66d
Create Date: 2025-07-26 14:56:16.467746

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '13973eed5512'
down_revision = '92abe68dc66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
