"""Auto-migration on startup

Revision ID: 155a82bf3298
Revises: 61236b460d29
Create Date: 2025-07-27 12:31:12.349266

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '155a82bf3298'
down_revision = '61236b460d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
