"""Auto-migration on startup

Revision ID: 1f7875059445
Revises: 9136715e9fbc
Create Date: 2025-07-26 09:23:27.265971

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '1f7875059445'
down_revision = '9136715e9fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
