"""Auto-migration on startup

Revision ID: 2470351a6f36
Revises: a687395a646b
Create Date: 2025-07-27 13:57:56.247516

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '2470351a6f36'
down_revision = 'a687395a646b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
