"""Auto-migration on startup

Revision ID: 2a266e31febf
Revises: fa22c9000d49
Create Date: 2025-07-26 09:32:48.046192

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '2a266e31febf'
down_revision = 'fa22c9000d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
