"""Auto-migration on startup

Revision ID: 2b35f3b14c56
Revises: fbfc1db935cd
Create Date: 2025-07-27 13:07:59.991521

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '2b35f3b14c56'
down_revision = 'fbfc1db935cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
