"""Auto-migration on startup

Revision ID: 337bdefc2190
Revises: 4db7969b0699
Create Date: 2025-07-26 13:21:05.727033

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '337bdefc2190'
down_revision = '4db7969b0699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
