"""Auto-migration on startup

Revision ID: 4db7969b0699
Revises: 06e4dfbd347f
Create Date: 2025-07-26 13:20:55.145398

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '4db7969b0699'
down_revision = '06e4dfbd347f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
