"""Auto-migration on startup

Revision ID: 4dd7dba6165c
Revises: 9834edf4f0f1
Create Date: 2025-07-26 09:11:22.139748

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '4dd7dba6165c'
down_revision = '9834edf4f0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
