"""Auto-migration on startup

Revision ID: 4ed535fe7d35
Revises: 337bdefc2190
Create Date: 2025-07-26 13:40:41.873748

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '4ed535fe7d35'
down_revision = '337bdefc2190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
