"""Auto-migration on startup

Revision ID: 5b96d97a0041
Revises: ad0a1b4f58c3
Create Date: 2025-07-27 12:50:07.442674

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '5b96d97a0041'
down_revision = 'ad0a1b4f58c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
