"""Auto-migration on startup

Revision ID: 61236b460d29
Revises: 9116bf46bda5
Create Date: 2025-07-26 15:41:50.401181

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '61236b460d29'
down_revision = '9116bf46bda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
