"""Auto-migration on startup

Revision ID: 6743f68e3f85
Revises: f27a2cb5f20c
Create Date: 2025-07-26 09:26:08.050759

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '6743f68e3f85'
down_revision = 'f27a2cb5f20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
