"""Auto-migration on startup

Revision ID: 842f472ee269
Revises: 2a266e31febf
Create Date: 2025-07-26 13:09:45.542456

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '842f472ee269'
down_revision = '2a266e31febf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
