"""Auto-migration on startup

Revision ID: 8b5bc6ab11fa
Revises: 6743f68e3f85
Create Date: 2025-07-26 09:28:34.565800

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '8b5bc6ab11fa'
down_revision = '6743f68e3f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
