"""Auto-migration on startup

Revision ID: 9116bf46bda5
Revises: 02d65e75ec5a
Create Date: 2025-07-26 15:37:47.366298

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '9116bf46bda5'
down_revision = '02d65e75ec5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
