"""Auto-migration on startup

Revision ID: 9136715e9fbc
Revises: bd8da8914b6e
Create Date: 2025-07-26 09:23:21.824373

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '9136715e9fbc'
down_revision = 'bd8da8914b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
