"""Auto-migration on startup

Revision ID: 92abe68dc66d
Revises: b5386cd02ca7
Create Date: 2025-07-26 14:39:23.256905

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '92abe68dc66d'
down_revision = 'b5386cd02ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
