"""Auto-migration on startup

Revision ID: 9317b4a77fb9
Revises: 4ed535fe7d35
Create Date: 2025-07-26 13:40:52.432257

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '9317b4a77fb9'
down_revision = '4ed535fe7d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
