"""Auto-migration on startup

Revision ID: 9834edf4f0f1
Revises: a5a28223f8c6
Create Date: 2025-07-26 09:11:16.518070

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '9834edf4f0f1'
down_revision = 'a5a28223f8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
