"""Auto-migration on startup

Revision ID: 9c6937e2d3d8
Revises: 8b5bc6ab11fa
Create Date: 2025-07-26 09:28:40.289416

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '9c6937e2d3d8'
down_revision = '8b5bc6ab11fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
