"""Auto-migration on startup

Revision ID: a687395a646b
Revises: c449460badde
Create Date: 2025-07-27 13:26:48.256121

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'a687395a646b'
down_revision = 'c449460badde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
