"""Auto-migration on startup

Revision ID: a9bedacb2030
Revises: 2470351a6f36
Create Date: 2025-07-27 14:48:04.969314

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'a9bedacb2030'
down_revision = '2470351a6f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
