"""Auto-migration on startup

Revision ID: ad0a1b4f58c3
Revises: 155a82bf3298
Create Date: 2025-07-27 12:31:23.454341

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'ad0a1b4f58c3'
down_revision = '155a82bf3298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
