"""Auto-migration on startup

Revision ID: b15ad60b498a
Revises: a9bedacb2030
Create Date: 2025-07-27 16:08:18.016228

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'b15ad60b498a'
down_revision = 'a9bedacb2030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
