"""Auto-migration on startup

Revision ID: b5386cd02ca7
Revises: 9317b4a77fb9
Create Date: 2025-07-26 14:39:13.538694

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'b5386cd02ca7'
down_revision = '9317b4a77fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
