"""Auto-migration on startup

Revision ID: bd8da8914b6e
Revises: eb64a754a4f3
Create Date: 2025-07-26 09:16:27.931073

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'bd8da8914b6e'
down_revision = 'eb64a754a4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
