"""Auto-migration on startup

Revision ID: c449460badde
Revises: 2b35f3b14c56
Create Date: 2025-07-27 13:26:38.256785

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'c449460badde'
down_revision = '2b35f3b14c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
