"""Auto-migration on startup

Revision ID: d010ffa843fa
Revises: 5b96d97a0041
Create Date: 2025-07-27 12:50:17.853143

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'd010ffa843fa'
down_revision = '5b96d97a0041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
