"""Auto-migration on startup

Revision ID: eb64a754a4f3
Revises: 4dd7dba6165c
Create Date: 2025-07-26 09:16:22.250174

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'eb64a754a4f3'
down_revision = '4dd7dba6165c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
