"""Auto-migration on startup

Revision ID: ef43048de430
Revises: 5f5951c71dc4
Create Date: 2025-07-26 15:15:17.955230

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'ef43048de430'
down_revision = '5f5951c71dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
