"""Auto-migration on startup

Revision ID: f27a2cb5f20c
Revises: 1f7875059445
Create Date: 2025-07-26 09:26:02.054923

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'f27a2cb5f20c'
down_revision = '1f7875059445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
