"""Auto-migration on startup

Revision ID: fa22c9000d49
Revises: 9c6937e2d3d8
Create Date: 2025-07-26 09:32:42.417149

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'fa22c9000d49'
down_revision = '9c6937e2d3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
