"""Auto-migration on startup

Revision ID: fbfc1db935cd
Revises: d010ffa843fa
Create Date: 2025-07-27 13:07:49.672153

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = 'fbfc1db935cd'
down_revision = 'd010ffa843fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
